// Code generated by "go generate github.com/savalin/gonum/unit/constant”; DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package constant

import "github.com/savalin/gonum/unit"

// FineStructure is the fine structure constant (α), it describes the strength of the electromagnetic interaction between elementary charged particles. The standard uncertainty of the constant is 1.7e-12 .
const FineStructure = unit.Dimless(0.0072973525664)
